### ISSUE TITLE
Migrate to Indent-blankline v3 from v2 

### ISSUE THREAD

**Issue by sajarin** [Shaedil/vim-config#3]
Error: You are trying to call the setup function of Indent-blankline version 2 but you have version 3 installed. 

See migration guide on Github: https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Migrate-to-version-3

**Comment by sajarin** [comment]
~~@shaedil fyi~~

oops should have looked at master, apologies

**Comment by sajarin** [comment]
actually nvm you just uncommented everything, can you add a new config here?

**Comment by Shaedil** [comment]
Resolved in 082d476.
